version: "3.0" # specify docker-compose version

# Define the services/ containers to be run
services:
  react: # name of the first service
    build: clientapp # specify the directory of the Dockerfile
    ports:
      - "8080:8080" # specify port mapping

  express: # name of the second service
    build: serverapp # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports mapping
    links:
      - database # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
